```{css}
div.my-header {
background-color: #272822;
  position: absolute;
top: 0px;
left: 0px;
height: 30px;
width: 100%;
text-align: left;
}

div.my-header span{
  font-size: 14pt;
  color: #F7F8FA;
    position: absolute;
  left: 15px;
  bottom: 2px;
}
````

```{r setup, include=FALSE, message=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning=FALSE, 
                      comment = "", cache = FALSE)
options(htmltools.preserve.raw = FALSE)
library(pacman)
p_load(char = c('tidyverse', 'here', 'janitor', 'fs', 
                'readxl', 'flipbookr', 'broom', 'tableone',
                'palmerpenguins', 'knitr', 'gt', 'kableExtra',
                'fontawesome', 'countdown', 'xaringanExtra', 'xaringanthemer',
                'pander','emo', 'reticulate'))

source(here('lib/R/update_header.R'))

library(reticulate)
use_condaenv('biof440', required=TRUE)

```

```{r xaringan-themer, include=FALSE}
library(xaringanthemer)
style_duo_accent(
   primary_color = "#0656F9", #3BA7F4", 
   secondary_color = "#F9A906", #F47C3B",
# style_mono_accent(
#   base_color = "#3BA7F4",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat"),
  code_font_google   = google_font("Fira Mono"),
  base_font_size = "20px"
)
xaringanExtra::use_tachyons()
xaringanExtra::use_panelset()
xaringanExtra::use_extra_styles(hover_code_line=TRUE, mute_unhighlighted_code = TRUE)
```

